# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_changed_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
